[package]
name = "applemusic-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = {version = "4.6.7", features = ["derive"]}
daemonize = "0.5.0"
futures-util = "0.3.34"
libc = "0.2.190"
serde = "1.0.229"
serde_json = "1.0.151"
thirtyfour = "0.37.5"
tokio = { version = "1.53.2", features = ["full"] }

[profile.release]
opt-level = 3        
lto = true            
codegen-units = 1     
strip = true          